#! /bin/sh

SCRIPT_DIR="$(dirname "$0")"
IMAGE_PREFIX=knockside
OUTPUT="$SCRIPT_DIR/compressed"

CAMERA="http://windowcam.local:8080/?action=snapshot"

UPLOAD_BUCKET=knockside.scot
UPLOAD_TARGET="s3://$UPLOAD_BUCKET/webcam/compressed"

set -e

now=$(date +%s)

shoot ()
{
    day="$(expr $now / 86400 '*' 86400)"
    mkdir -p "$OUTPUT"/"$day"

    curl \
        --no-progress-meter \
        --output "$OUTPUT"/"$day"/"$IMAGE_PREFIX"-$now.jpg \
        "$CAMERA"

    # Create a stable “most-recent output” file.
    cp --archive \
        "$OUTPUT"/"$day"/"$IMAGE_PREFIX"-$now.jpg \
        "$OUTPUT"/"$IMAGE_PREFIX".jpg
}

generate_manifest ()
{
    find "$1" \
         -type f \
         \( -name '*.jpg' \
            -o -name '*.png' \
            -o -name '*.webp' \) \
         -print0 \
         | xargs -0 basename --multiple \
         | grep '\-[0-9]\+\.' \
         | cut -d- -f2- \
         | cut -d. -f1 \
         | sort \
         | uniq \
         | awk '
    BEGIN {
        printf "[";
    }

    NR > 1 {
        printf ",";
    }

    {
        printf "\"%s\"", $1;
    }

    END {
        printf "]\n";
    }
    ' >"$1/manifest.json"
}

upload ()
{
    # We want to run as few sync operations as possible, as each one takes
    # ~3.5s. That's not a lot in isolation, but really adds up when you have a
    # few months of images in the output directory. Under the assumption that
    # uploading occurs nearly as regularly as shooting, upload only the two
    # most recent days. This will handle the rollover scenario where shooting
    # occurs just before midnight, and uploading happens just after.
    #
    # TODO: Would be nice to have an “--all” flag for offline use.
    #
    # TODO: This requires that $OUTPUT contain no spaces, which sucks.
    for day_source in $(ls -1 --directory --sort=time --reverse "$OUTPUT"/*/ | tail -n 2)
    do
        day="$(basename "$day_source")"
        echo "Synching $day_source to $UPLOAD_TARGET/$day..."
        aws s3 sync "$day_source" "$UPLOAD_TARGET"/"$day"
    done

    aws s3 cp "$OUTPUT"/"$IMAGE_PREFIX".jpg "$UPLOAD_TARGET"/ --cache-control "max-age=60"
    aws s3 cp "$OUTPUT"/manifest.json "$UPLOAD_TARGET"/ --cache-control "max-age=60"
}

main ()
{
    if [ $# -ge 1 ]
    then
        case "$1" in
        "shoot")
            shoot
            ;;
        "manifest")
            generate_manifest "$OUTPUT"
            ;;
        "upload")
            upload
            ;;
        esac
    else
        shoot
        generate_manifest "$OUTPUT"
        upload
    fi
}

main "$@"
